In [11]:
import numpy as np

Write a Python program to:

A. Create a 1D NumPy array of 10 integers ranging from 1 to 10.

In [12]:
arr_1 = np.arange(1, 11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

B. Create a 2D NumPy array of shape (3, 3) with integers from 1
to 9.

In [13]:
arr_2 = np.arange(1, 10).reshape(3, 3)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

C. Create a 3D NumPy array with random floating-point numbers
of shape (3, 5, 3).

In [14]:
arr_3 = np.random.rand(3, 5, 3)
arr_3

array([[[0.09339086, 0.91223658, 0.9034782 ],
        [0.21345787, 0.19729722, 0.08818331],
        [0.90003288, 0.90143755, 0.28409956],
        [0.95714191, 0.1496182 , 0.47601461],
        [0.64570009, 0.93387462, 0.27854489]],

       [[0.0820775 , 0.1669673 , 0.71950738],
        [0.74032569, 0.7305467 , 0.24046368],
        [0.64240955, 0.05912513, 0.27992428],
        [0.50452846, 0.71020465, 0.2984589 ],
        [0.69117924, 0.20904287, 0.17292732]],

       [[0.14641825, 0.90990665, 0.27210721],
        [0.28762371, 0.24333131, 0.90403741],
        [0.66940988, 0.16664107, 0.49872909],
        [0.65850349, 0.83381727, 0.30705808],
        [0.62443345, 0.29278461, 0.24278024]]])

2. Display the shape, size, and datatype of each array.

In [15]:
print("1D - Shape:", arr_1.shape, "Size:", arr_1.size, "Dtype:", arr_1.dtype)
print("2D - Shape:", arr_2.shape, "Size:", arr_2.size, "Dtype:", arr_2.dtype)
print("3D - Shape:", arr_3.shape, "Size:", arr_3.size, "Dtype:", arr_3.dtype)

1D - Shape: (10,) Size: 10 Dtype: int32
2D - Shape: (3, 3) Size: 9 Dtype: int32
3D - Shape: (3, 5, 3) Size: 45 Dtype: float64
