In [10]:
import numpy as np

1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.

In [11]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

2. Write a Python program to:

A. Reshape the array into a 2D array of shape (4, 3).

In [12]:
arr_2 = arr.reshape(4, 3)
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

B. Reshape the array into a 3D array of shape (2, 2, 3).

In [13]:
arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

C. Transpose the reshaped 2D array and display its shape.

In [14]:
arr_2.T


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [15]:
arr_2.T.shape

(3, 4)