In [8]:
import numpy as np

1. Use NumPy's built-in functions to:

A. Create an array of 10 equally spaced values between 0 and 1.

In [9]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

B. Create an identity matrix of size 4x4.

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

C. Generate a 1D array of 20 random integers between 1 and 100,
sort it, and find the 5 largest elements.

In [11]:
arr = np.random.randint(1, 101, 20)
np.sort(arr)

array([16, 20, 22, 22, 28, 38, 41, 41, 41, 61, 63, 76, 77, 84, 88, 89, 90,
       95, 97, 99])

In [12]:
np.sort(arr)[-5:][::-1]

array([99, 97, 95, 90, 89])