In [20]:
import numpy as np

1. Create a NumPy array with 15 random integers between 10 and 50.

In [21]:
arr = np.random.randint(10, 51, 15)
arr

array([21, 50, 21, 34, 21, 45, 44, 29, 35, 22, 42, 22, 12, 36, 12])

2. Write a Python program to:

A. Find all elements greater than 25.

In [22]:
arr[arr > 25]

array([50, 34, 45, 44, 29, 35, 42, 36])

B. Replace all elements less than 30 with 0.

In [23]:
arr[arr < 30] = 0
arr

array([ 0, 50,  0, 34,  0, 45, 44,  0, 35,  0, 42,  0,  0, 36,  0])

C. Count the number of elements divisible by 5.

In [24]:
np.sum(arr % 5 == 0)

11