In [7]:
import numpy as np

1. Create a NumPy array from the following list:

data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [8]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2. Write a Python program to:

A. Retrieve the first three elements of the array.

In [9]:
arr[:3]

array([10, 20, 30])

B. Retrieve every alternate element of the array.

In [10]:
arr[::2]

array([10, 30, 50, 70, 90])

C. Reverse the array.

In [11]:
arr[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])